backend:
  name: github
  repo: nikhilesh-wani/nikhilesh-wani-portfolio
  branch: main
  auth_type: pkce
  app_id: Ov23licB8o9wwb0CO4SD
  base_url: https://nikhilesh-wani.github.io
  site_domain: nikhilesh-wani.github.io

site_url: https://nikhilesh-wani.github.io/nikhilesh-wani-portfolio

media_folder: "assets/blog"
public_folder: "/assets/blog"

collections:
  - name: "posts"
    label: "Blog Posts"
    folder: "blog/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Description", name: "description", widget: "text" }
      - { label: "Tags", name: "tags", widget: "list", default: [] }
      - { label: "Body", name: "body", widget: "markdown" }
